version: '3'

services:
  web:
    build: .
    container_name: datachat
    ports:
      - "8501:8501"
    working_dir: /app
    command: streamlit run app/app.py
    volumes:
      #- ./app:/app
      - ${CONFIG}:/config
      - ${DATADIR}:/data
      - ${CACHEDIR}:/root/.cache
      - ${INSTALLATION}:/app/installation
      - ./tests:/app/tests
      - ./app/utils.py:/app/app/utils.py
      - ./app/app.py:/app/app/app.py
      - ./app/Paracrawl.py:/app/app/Paracrawl.py
      - ./dev/Croissant.py:/usr/local/lib/python3.11/site-packages/pyDataverse/Croissant.py
#    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_ENABLECORS=false
      - OLLAMA
      - MODEL
      - INTRO
      - TITLE
      - FAKEDNS
      - DATADIR
      - IDATADIR
      - SOURCES
      - REASONING
      - FILTER
    restart: always

  api:
    build: .
    container_name: apidatachat
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      #- ./app:/app
      - ${CONFIG}:/config
      - ${DATADIR}:/data
      - ${CACHEDIR}:/root/.cache
      - ${INSTALLATION}:/app/installation
      - ./tests:/app/tests
      - ./app/api.py:/app/main.py
      - ./app/utils.py:/app/utils.py
      - ./dev/Croissant.py:/usr/local/lib/python3.11/site-packages/pyDataverse/Croissant.py
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_ENABLECORS=false
      - OLLAMA
      - MODEL
      - INTRO
      - TITLE
      - FAKEDNS
      - DATADIR
      - IDATADIR
      - SOURCES
      - REASONING
      - FILTER
      - DATAVERSE
    restart: always
